### ISSUE TITLE
Transcription Failed Error

### ISSUE THREAD

**Issue by JeremiLorenti** [e-johnstonn/SalesCopilot#1]
![image](https://github.com/e-johnstonn/SalesCopilot/assets/120612878/e9f72655-50dd-45da-9b4f-129fb1a31725)

I get transcription failed error. I have installed the requirements.txt file and entered my API key both with and without the <>'s to test.

**Comment by e-johnstonn** [comment]
The API key should be enclosed in quotations like:

OPENAI_API_KEY = ‘sk-key’ 

Let me know if that fixes it.

sorry if that wasn’t clear, I’ll update the readme with an example

**Comment by JeremiLorenti** [comment]
Unfortunately that did not work. I'm still receiving the same error.

https://i.imgur.com/yIiGUWB.png

**Comment by e-johnstonn** [comment]
try running it with the latest version, I just fixed something that should at least make the error message more descriptive and easier to diagnose

**Comment by JeremiLorenti** [comment]
![image](https://github.com/e-johnstonn/SalesCopilot/assets/120612878/0d66c853-877a-4a29-a8e3-980839c92eee)


Still erroring out unfortunately. I re-cloned the repo using github desktop, updated my API key file, and re-ran the requirements.txt all with no errors.

**Comment by e-johnstonn** [comment]
i added error handling for every type of api error, so you should now be able to see exactly what the issue is.

**Comment by JeremiLorenti** [comment]
Working now! Wow this is amazing! Great job!

The extra error handling allowed me to see exactly what the issue was... me
being a dumbass and using an expired API key.

Thanks for your help, appreciate it!

-Jeremi

**Comment by e-johnstonn** [comment]
no problem! my bad with the poor error handling, could've saved us both some time if it was done properly from the start

**Comment by JeremiLorenti** [comment]
Haha, no problem! Don’t be so hard on yourself! I can’t express how much
this is going to help me with my daily meetings.
