### ISSUE TITLE
Using Nova instead of Whisper

### ISSUE THREAD

**Issue by DawgZter** [e-johnstonn/SalesCopilot#2]
Are we able to use Nova API instead of Whisper API? It's supposed to be much faster, accurate and cheaper.

https://blog.deepgram.com/nova-speech-to-text-whisper-api/?utm_source=twitter&utm_campaign=0423%20nova%20whisper%20announcement&utm_medium=organic%20social&utm_content=announcement%20tweet

Just wondering what would need to be done to support Nova API being used here.

**Comment by e-johnstonn** [comment]
I'll look into it - from a glance, it seems like it would be as simple as adding a few lines of code to allow choice between OpenAI and Nova. Nova looks really cool, thanks for sharing.
