### ISSUE TITLE
Support for models other than OpenAI?

### ISSUE THREAD

**Issue by asmith26** [e-johnstonn/SalesCopilot#3]
Hi there, 

Just wondering if you plan to add support for [LLMs](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard) other than just OpenAI's GPT 3.5/4?

This project looks really interesting, thanks for sharing! :)

**Comment by e-johnstonn** [comment]
It's a good idea, only issue I see is the speed. If you have experience working with other LLMs I'd be interested to hear your take on it.
